"""create initial schema

Revision ID: f62da81744b3
Revises:     
Create Date: 2026-03-13 22:41:51.665705+00:00
"""

from collections.abc import Sequence
from typing import Optional, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f62da81744b3'
down_revision: Optional[str] = None
branch_labels: Optional[Union[str, Sequence[str]]] = None
depends_on: Optional[Union[str, Sequence[str]]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('maps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_maps_owner', 'maps', ['owner_id'], unique=False)
    op.create_table('map_members',
    sa.Column('map_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='map_role'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('map_id', 'user_id')
    )
    op.create_index('idx_map_members_user', 'map_members', ['user_id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('map_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), server_default=sa.text("'#6366f1'"), nullable=False),
    sa.Column('x', sa.Double(), server_default=sa.text('0'), nullable=False),
    sa.Column('y', sa.Double(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nodes_created', 'nodes', ['map_id', 'created_at'], unique=False)
    op.create_index('idx_nodes_map', 'nodes', ['map_id'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('map_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_id <> target_id', name='no_self_loops'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_id', 'source_id', 'target_id', name='unique_directed_edge')
    )
    op.create_index('idx_edges_map', 'edges', ['map_id'], unique=False)
    op.create_index('idx_edges_source', 'edges', ['source_id'], unique=False)
    op.create_index('idx_edges_target', 'edges', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_edges_target', table_name='edges')
    op.drop_index('idx_edges_source', table_name='edges')
    op.drop_index('idx_edges_map', table_name='edges')
    op.drop_table('edges')
    op.drop_index('idx_nodes_map', table_name='nodes')
    op.drop_index('idx_nodes_created', table_name='nodes')
    op.drop_table('nodes')
    op.drop_index('idx_map_members_user', table_name='map_members')
    op.drop_table('map_members')
    op.drop_index('idx_maps_owner', table_name='maps')
    op.drop_table('maps')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.execute("DROP TYPE IF EXISTS map_role")
    # ### end Alembic commands ###
